# Jobs: 
# - "test"
#
# Runs tests and code analysis ( like PHPUnit, Behat, code checker, etc ) 
# against a Moodle plugin in CI.
# - See https://moodlehq.github.io/moodle-plugin-ci/.
# 
# The current matrix we are using is:
# - ubuntu-latest
# - PHP8.0, PHP8.1, PHP8.2, PHP8.3
# - Moodle from 4.2 to latest(4.4)

name: Moodle Plugin CI

# Run this workflow every time a new commit pushed to the repository or PR
# is created or on demand. It also executes every morning at 6:30 so we're 
# the first to know if tests are failing due to an update on PHP or Moodle.
on:
  schedule:
    - cron: '30 6 * * *'
  push:
  workflow_dispatch:

jobs:
  test:
    # We will use ubuntu-latest as a virtual environment to use.
    runs-on: ubuntu-latest

    services:
      # The test will be scoped to postgres only.
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3']
        moodle-branch: [MOODLE_402_STABLE, MOODLE_403_STABLE, MOODLE_404_STABLE, main]
        database: [pgsql]
        exclude:
          # Exclude Moodle+PHP incompatible versions
          # See: https://docs.moodle.org/dev/Moodle_and_PHP
          - moodle-branch: 'MOODLE_404_STABLE'
            php: '8.0'
          - moodle-branch: 'main'
            php: '8.0'
          - moodle-branch: 'main'
            php: '8.1'
          - moodle-branch: 'MOODLE_402_STABLE'
            php: '8.3'
          - moodle-branch: 'MOODLE_403_STABLE'
            php: '8.3'
            
    steps:
      # 0. Initial step. Check out this repository code in ./plugin directory
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: plugin

      # 0.1 Log
      - name: Print my ip
        run: host myip.opendns.com resolver1.opendns.com | grep "myip.opendns.com has" | awk '{print $4}'

      # 0.2. install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 1. Setup PHP using the matrix described on the strategy section.
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: max_input_vars=10000
          coverage: none

      # 2. Setup Moodle-plugin-ci
      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
        env:
          IGNORE_PATHS: classes/privacy,ignore,node_modules,integration,render
          COVERAGE: false
          CODECHECKER_IGNORE_PATHS: classes/privacy,ignore,node_modules,integration,render
          PHPUNIT_IGNORE_PATHS: classes/privacy,ignore,node_modules,integration,render


      # 3. Install Filter plugin
      - name: Add MathType filter plugin
        id: install-plugin-filter
        continue-on-error: true
        run: |
          moodle-plugin-ci add-plugin --branch ${GITHUB_REF##*/} wiris/moodle-filter_wiris
      - name: Add MathType filter plugin using the stable branch
        if: steps.install-plugin-filter.outcome != 'success'
        run: |
          moodle-plugin-ci add-plugin --branch stable wiris/moodle-filter_wiris

      # 4. Install Moodle-plugin-ci
      - name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      # 5. Run all tests.
      # 5.1. Lint
      - name: PHP Lint
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

      # 5.2. PHP Detectors
      - name: PHP Copy/Paste Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpcpd

      - name: PHP Mess Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd

      # 5.3. Code validations
      - name: Moodle Code Checker
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker --max-warnings 0

      - name: Validating
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

      - name: Mustache Lint
        if: ${{ always() }}
        run: moodle-plugin-ci mustache

      # 5.4. Code testing
      # Run PHPUnit tests on Moodle3_9 only, for the moment.
      - name: PHPUnit tests
        if: ${{ always() }}
        run: moodle-plugin-ci phpunit
      # Run all Behat tests on latest Moodle branch
      - name: Behat features
        run: moodle-plugin-ci behat --profile default -vvv